[package]
name = "rustyrdap"
version = "0.1.0"
authors = ["Carlos M. Martinez <carlos@xt6.us>"]

[dependencies]
  docopt = "=0.6.86"
  docopt_macros = "~0.6.86"
  hyper = "0.9.13"
  rustc-serialize = "0.3.21"